-- MySQL Script generated by MySQL Workbench
-- Wed Oct 24 14:57:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_dep
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_dep` ;

-- -----------------------------------------------------
-- Schema db_dep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_dep` DEFAULT CHARACTER SET utf8 ;
USE `db_dep` ;

-- -----------------------------------------------------
-- Table `db_dep`.`maestros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dep`.`maestros` ;

CREATE TABLE IF NOT EXISTS `db_dep`.`maestros` (
  `id_maestro` INT NOT NULL AUTO_INCREMENT,
  `nombre_maestro` VARCHAR(45) NOT NULL,
  `apellido_maestro` VARCHAR(45) NOT NULL,
  `correo_upa` VARCHAR(45) NOT NULL,
  `correo_personal` VARCHAR(45) NOT NULL,
  `grado_academico` VARCHAR(45) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_maestro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dep`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dep`.`materias` ;

CREATE TABLE IF NOT EXISTS `db_dep`.`materias` (
  `id_materia` INT ZEROFILL NOT NULL,
  `nombre_materia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dep`.`carreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dep`.`carreras` ;

CREATE TABLE IF NOT EXISTS `db_dep`.`carreras` (
  `id_carrera` INT ZEROFILL NOT NULL,
  `nombre_carrera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dep`.`grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dep`.`grupos` ;

CREATE TABLE IF NOT EXISTS `db_dep`.`grupos` (
  `id_grupo` INT ZEROFILL NOT NULL,
  `nombre_grupo` VARCHAR(45) NOT NULL,
  `cod_carrera` INT ZEROFILL NOT NULL,
  `materia_profesor_id_material_profesore` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`id_grupo`),
  INDEX `fk_grupos_carreras_idx` (`cod_carrera` ASC) VISIBLE,
  CONSTRAINT `fk_grupos_carreras`
    FOREIGN KEY (`cod_carrera`)
    REFERENCES `db_dep`.`carreras` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dep`.`edificios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dep`.`edificios` ;

CREATE TABLE IF NOT EXISTS `db_dep`.`edificios` (
  `id_edificio` INT ZEROFILL NOT NULL,
  `nombre_edificio` VARCHAR(45) NULL,
  PRIMARY KEY (`id_edificio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dep`.`aulas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dep`.`aulas` ;

CREATE TABLE IF NOT EXISTS `db_dep`.`aulas` (
  `id_aula` INT ZEROFILL NOT NULL,
  `nombre_aula` VARCHAR(45) NOT NULL,
  `cod_edificio` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`id_aula`),
  INDEX `fk_aulas_edificios1_idx` (`cod_edificio` ASC) VISIBLE,
  CONSTRAINT `fk_aulas_edificios1`
    FOREIGN KEY (`cod_edificio`)
    REFERENCES `db_dep`.`edificios` (`id_edificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dep`.`materia_profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dep`.`materia_profesor` ;

CREATE TABLE IF NOT EXISTS `db_dep`.`materia_profesor` (
  `id_material_profesore` INT ZEROFILL NOT NULL,
  `cod_materia` INT ZEROFILL NOT NULL,
  `cod_maestro` INT NOT NULL,
  `cod_aula` INT ZEROFILL NOT NULL,
  `cod_grupo` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`id_material_profesore`),
  INDEX `fk_materia_profesor_materias1_idx` (`cod_materia` ASC) VISIBLE,
  INDEX `fk_materia_profesor_maestros1_idx` (`cod_maestro` ASC) VISIBLE,
  INDEX `fk_materia_profesor_aulas1_idx` (`cod_aula` ASC) VISIBLE,
  INDEX `fk_materia_profesor_grupos1_idx` (`cod_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_materia_profesor_materias1`
    FOREIGN KEY (`cod_materia`)
    REFERENCES `db_dep`.`materias` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_profesor_maestros1`
    FOREIGN KEY (`cod_maestro`)
    REFERENCES `db_dep`.`maestros` (`id_maestro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_profesor_aulas1`
    FOREIGN KEY (`cod_aula`)
    REFERENCES `db_dep`.`aulas` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_materia_profesor_grupos1`
    FOREIGN KEY (`cod_grupo`)
    REFERENCES `db_dep`.`grupos` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dep`.`solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dep`.`solicitudes` ;

CREATE TABLE IF NOT EXISTS `db_dep`.`solicitudes` (
  `id_solitudes` INT ZEROFILL NOT NULL,
  `cod_usuario` VARCHAR(45) NOT NULL,
  `cod_materia` VARCHAR(45) NOT NULL,
  `cod_grupo` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_solitudes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dep`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dep`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `db_dep`.`usuarios` (
  `id_usuario` INT ZEROFILL NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `apellidos:usuario` VARCHAR(45) NOT NULL,
  `solicitudes_id_solitudes` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_solicitudes1_idx` (`solicitudes_id_solitudes` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_solicitudes1`
    FOREIGN KEY (`solicitudes_id_solitudes`)
    REFERENCES `db_dep`.`solicitudes` (`id_solitudes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
